const CscData = [
    { classification: '주문 관련', id: '1', category: 'order', title: '주문을 어떻게 할 수 있나요?', detail: '원하는 제품을 장바구니에 담고 결제 페이지로 이동하여 주문을 완료하시면 됩니다. 회원 가입 후 로그인하면 주문이 더 간편합니다.' },
    { classification: '주문 관련', id: '2', category: 'order', title: '주문 내역을 확인하고 싶어요. 어디서 확인할 수 있나요?', detail: '로그인 후 "내 계정" 페이지에서 "주문 내역"을 클릭하시면 주문 상태와 상세 내역을 확인하실 수 있습니다.' },
    { classification: '주문 관련', id: '3', category: 'order', title: '주문을 취소하고 싶어요. 어떻게 해야 하나요?', detail: '주문 상태가 "배송 준비 중" 이전이라면 "내 계정"의 "주문 내역"에서 직접 취소 가능합니다. 이미 배송 중인 경우 고객센터로 문의해주세요.' },
    { classification: '배송 관련', id: '4', category: 'delivery', title: '배송비는 얼마인가요?', detail: '주문 금액이 50,000원 이상일 경우 무료 배송이며, 그 이하일 경우 2,500원의 배송비가 부과됩니다.' },
    { classification: '배송 관련', id: '5', category: 'delivery', title: '배송 기간은 얼마나 걸리나요?', detail: '결제 완료 후 평균 2-3일 이내에 배송됩니다. 다만, 지역 및 택배사의 사정에 따라 다소 지연될 수 있습니다.' },
    { classification: '배송 관련', id: '6', category: 'delivery', title: '해외 배송도 가능한가요?', detail: '죄송합니다. 현재는 해외 배송 서비스를 제공하지 않고 있습니다.' },
    { classification: '결제/환불', id: '7', category: 'pay', title: '예약상품의 주문 취소는 언제까지 가능한가요?', detail: '예약상품의 주문 취소는 상품 발송 전까지 가능합니다. 발송 후에는 취소가 불가하니 주의해주세요.' },
    { classification: '결제/환불', id: '8', category: 'pay', title: '주문 내 상품을 일부 부분취소 할 수 있나요?', detail: '주문 내 상품의 부분취소는 불가능합니다. 전체 취소 후 재주문해 주시기 바랍니다.' },
    { classification: '결제/환불', id: '9', category: 'pay', title: '결제 시 오류가 나타납니다.', detail: '결제 시 오류가 발생할 경우, 고객센터로 문의해주시면 신속히 도와드리겠습니다.' },
    { classification: '결제/환불', id: '10', category: 'pay', title: '선물하기로 주문을 하였는데, 받는 사람이 받지 않아요.', detail: '받는 분의 주소와 연락처를 다시 확인해주시고, 고객센터로 문의해주세요.' },
    { classification: '결제/환불', id: '11', category: 'pay', title: '결제를 완료하였는데, 재고가 없다는 알림과 함께 주문이 취소되었습니다.', detail: '죄송합니다. 재고 부족으로 인해 주문이 취소될 수 있습니다. 다음 번 재입고 시 안내드리겠습니다.' },
    { classification: '결제/환불', id: '12', category: 'pay', title: '결제 시 포인트를 사용한 경우, 환불 시 같이 돌려받을 수 있나요?', detail: '포인트를 사용하여 결제한 경우, 환불 시 사용된 포인트는 자동으로 복원됩니다.' },
    { classification: '결제/환불', id: '13', category: 'pay', title: '주문을 취소/반품하면 바로 환불 받을 수 있나요?', detail: '주문 취소/반품 시 환불은 반품된 상품 확인 후 영업일 기준 3-5일 내에 처리됩니다.' },
    { classification: '교환/환불', id: '14', category: 'exchange', title: '교환 / 반품 요청을 하였는데, 요청을 취소하고 싶어요.', detail: '교환/반품 요청 취소는 고객센터로 문의해주시면 도와드리겠습니다.' },
    { classification: '교환/환불', id: '15', category: 'exchange', title: '교환 / 반품 시, 어디로 상품을 발송하면 되나요?', detail: '교환/반품 상품은 지정된 반송지로 보내주셔야 합니다. 자세한 주소는 고객센터로 문의해주세요.' },
    { classification: '교환/환불', id: '16', category: 'exchange', title: '교환 / 반품하고 싶습니다. 어떻게 하면 되나요?', detail: '교환/반품은 "내 계정"의 "주문 내역"에서 요청하실 수 있습니다. 자세한 절차는 고객센터로 문의해주세요.' },
    { classification: '교환/환불', id: '17', category: 'exchange', title: '다른 상품으로 교환할 수 있나요?', detail: '다른 상품으로의 교환은 불가능합니다. 기존 상품 반품 후 새로운 상품을 주문해주시기 바랍니다.' },
    { classification: '교환/환불', id: '18', category: 'exchange', title: '교환 / 반품이 불가능한 상품은 어떤 것이 있나요?', detail: '개봉된 상품, 사용된 상품, 또는 특정 제품군(예: 예약 상품)은 교환/반품이 불가능합니다. 자세한 내용은 고객센터에 문의해주세요.' },
    { classification: '쿠폰/포인트', id: '19', category: 'coupon', title: '적립된 포인트의 유효기간은 모두 동일한가요?', detail: '적립된 포인트의 유효기간은 각 포인트별로 다를 수 있으며, 상세 내용은 "내 계정"의 포인트 내역에서 확인 가능합니다.' },
    { classification: '쿠폰/포인트', id: '20', category: 'coupon', title: '할인 및 기획전 상품의 경우 포인트는 어떻게 지급되나요?', detail: '할인 및 기획전 상품 구매 시에도 동일하게 포인트가 적립됩니다.' },
    { classification: '쿠폰/포인트', id: '21', category: 'coupon', title: '환불, 교환신청하면 쿠폰이나 포인트는 어떻게 되나요?', detail: '환불/교환 시 사용된 쿠폰은 복원되지 않으며, 포인트는 환불 시 자동 복원됩니다.' },
    { classification: '쿠폰/포인트', id: '22', category: 'coupon', title: '쿠폰의 사용 기한을 연장해 주실 수 있나요?', detail: '쿠폰의 사용 기한은 연장 불가합니다. 기한 내에 사용해주시기 바랍니다.' },
    { classification: '쿠폰/포인트', id: '23', category: 'coupon', title: '쿠폰 시리얼 번호를 받았습니다. 어디서 등록할 수 있나요?', detail: '쿠폰 시리얼 번호는 "내 계정"의 쿠폰 등록 페이지에서 입력하시면 됩니다.' },
    { classification: '쿠폰/포인트', id: '24', category: 'coupon', title: '쿠폰을 양도하고 싶습니다.', detail: '쿠폰은 양도가 불가합니다. 본인만 사용 가능합니다.' },
    { classification: '쿠폰/포인트', id: '25', category: 'coupon', title: '결제 시 쿠폰을 사용한 경우, 환불 시 돌려받을 수 있나요?', detail: '결제 시 사용한 쿠폰은 환불 시 복원되지 않으니, 환불 전 신중히 결정해주시기 바랍니다.' },
    { classification: '배송', id: '26', category: 'delivery', title: '상품이 파손된 상태로 배송되었습니다.', detail: '상품이 파손된 경우, 즉시 고객센터로 연락주시면 교환 또는 환불 절차를 안내해드리겠습니다.' },
    { classification: '배송', id: '27', category: 'delivery', title: '배송완료 상태인데, 상품을 받지 못했습니다.', detail: '배송완료 상태에서 상품을 받지 못한 경우, 고객센터로 문의해주시면 확인 후 조치해드리겠습니다.' },
    { classification: '배송', id: '28', category: 'delivery', title: '주문 내 상품들을 각각 다른 배송지로 배송할 수 있나요?', detail: '죄송합니다. 주문 당 배송지는 한 곳으로만 설정 가능합니다.' },
    { classification: '배송', id: '29', category: 'delivery', title: '해외 배송을 받을 수 있을까요?', detail: '현재는 해외 배송 서비스를 제공하지 않고 있습니다.' },
    { classification: '배송', id: '30', category: 'delivery', title: '택배사가 여러 개인가요?', detail: '저희는 한 개의 택배사와 계약하여 배송 서비스를 제공하고 있습니다.' },
    { classification: '배송', id: '31', category: 'delivery', title: '묶음 배송이 가능한가요?', detail: '여러 상품을 한 번에 주문하신 경우 묶음 배송이 가능합니다.' },
    { classification: '배송', id: '32', category: 'delivery', title: '배송 전 주소를 변경하고 싶어요.', detail: '배송 전 주소 변경은 "내 계정"에서 가능합니다. 이미 배송 중인 경우 주소 변경이 불가합니다.' },
    { classification: '배송', id: '33', category: 'delivery', title: '지정 택배사 외 다른 택배사로도 받을 수 있나요?', detail: '죄송합니다. 지정된 택배사 외 다른 택배사로는 배송이 불가능합니다.' },
    { classification: 'A/S', id: '34', category: 'afterService', title: '상품 A/S를 신청하고 싶어요.', detail: 'A/S 신청은 고객센터를 통해 접수하실 수 있으며, 접수 후 안내에 따라 상품을 보내주시면 됩니다.' },
    { classification: 'A/S', id: '35', category: 'afterService', title: 'A/S센터 위치와 운영시간이 궁금해요.', detail: 'A/S센터 위치와 운영시간은 홈페이지의 "고객센터" 메뉴에서 확인하실 수 있습니다.' },
    { classification: 'A/S', id: '36', category: 'afterService', title: 'A/S센터로 직접 방문해서 수리받을 수 있나요?', detail: '직접 방문하여 A/S를 받으실 수 있으며, 방문 전 고객센터로 사전 예약 부탁드립니다.' },
    { classification: 'A/S', id: '37', category: 'afterService', title: 'A/S 기간이 종료된 경우, 해당 상품의 부품을 구할 수 없나요?', detail: 'A/S 기간이 종료된 경우에도 일부 부품은 유상으로 구매 가능합니다. 고객센터로 문의해주시기 바랍니다.' },
    { classification: 'A/S', id: '38', category: 'afterService', title: '반다이남코코리아몰에서 구매하지 않은 완구도 A/S를 받을 수 있나요?', detail: '반다이남코코리아몰에서 구매하지 않은 제품은 A/S가 불가능합니다. 구매처에 문의해주세요.' },
    { classification: 'A/S', id: '39', category: 'afterService', title: 'A/S 비용은 어떻게 입금하나요?', detail: 'A/S 비용 입금은 고객센터 안내에 따라 계좌 이체로 진행해주시면 됩니다.' },
    { classification: 'A/S', id: '40', category: 'afterService', title: '외국에서 발매한 반다이의 완구 상품을 A/S 받을 수 있나요?', detail: '죄송합니다. 외국에서 발매된 제품은 A/S가 불가능합니다.' },
    { classification: 'A/S', id: '41', category: 'afterService', title: 'A/S 처리 기간은 얼마나 걸리나요?', detail: 'A/S 처리 기간은 평균 7-10일이 소요되며, 제품의 상태에 따라 다소 지연될 수 있습니다.' },
    { classification: '상품 관련', id: '42', category: 'product', title: '예약 상품의 출고 일정이 변동 되거나, 예약 주문이 취소 될 수 있나요?', detail: '예약 상품의 출고 일정은 변동될 수 있으며, 이에 따라 예약 주문이 취소될 수 있습니다. 변경 사항 발생 시 안내드리겠습니다.' },
    { classification: '상품 관련', id: '43', category: 'product', title: '사은품을 별도로 구매할 수 있나요?', detail: '사은품은 별도로 구매할 수 없으며, 프로모션 기간 내 해당 상품 구매 시에만 제공됩니다.' },
];

export default CscData;